### ISSUE TITLE
No Discussion River activities

### ISSUE THREAD

**Issue by daveonche** [hypeJunction/hypeDiscussions#1]
Hello Ismayil... discussion activities are not created in river when hypeDiscussion plugin is enabled. Would that be a bug or its meant to be that way? Thanks.

**Comment by hypeJunction** [comment]
Bug. Need to check

**Comment by hypeJunction** [comment]
Fixed in https://github.com/hypeJunction/hypeDiscussions/commit/58170ae9b28685d1e524a10ddde881f1d4831c45
