### ISSUE TITLE
Reply Link is only visible to Admins

### ISSUE THREAD

**Issue by daveonche** [hypeJunction/hypeDiscussions#2]
Reply to discussions is only available to admins. Non admin users only get to like discussion posts.

**Comment by hypeJunction** [comment]
Can't confirm this. Make sure the user is a member of the group.

**Comment by daveonche** [comment]
Actually, this happens when discussion is posted outside of groups. Admin settings allows for posting discussions outside of groups, i guess i will just disable that function. Thanks.

**Comment by hypeJunction** [comment]
Try the new release I made.

**Comment by daveonche** [comment]
Thanks.. Working perfectly now.
