### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by josmunoz** [hypeJunction/hypeDiscussions#4]
after unpacking hypediscussion plugin i get a report in de admin plugins that there are missing dependencies for this module. What to do about this?

**Comment by hypeJunction** [comment]
Install missing dependencies. Click on the plugin name in the list it will show you all the deps

**Comment by josmunoz** [comment]
clicking on it shows Bad gateway


sorry tried it again and it shows the dependencies
thanks
