### ISSUE TITLE
Fatal error:  Call to a member function getOwnerEntity() on null

### ISSUE THREAD

**Issue by ghost** [hypeJunction/hypeDiscussions#5]
Hello,
I had to deactivate hypediscussions 2.1.0 on latest Elgg due to the following error:

PHP Fatal error:  Call to a member function getOwnerEntity() on null in /mod/hypeDiscussions/views/default/object/discussion.php on line 66

This also made group discussions, group tags, dashboard not available (error 500)

Cheers

**Comment by hypeJunction** [comment]
You must have wiped a user without properly recursing into all the content.

**Comment by michelesbw** [comment]
It looks like the culprit is "Website" field, if empty width respects column's

**Comment by ghost** [comment]
Uhm...something I had to do as admin or elgg as task upon deletion of a user? Hope second :)
Thanks a lot for fixing it so quickly!

**Comment by hypeJunction** [comment]
Never mind, it was me stupid.

**Comment by ghost** [comment]
Yeah...I know the feeling :D
