### ISSUE TITLE
Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field()

### ISSUE THREAD

**Issue by ernestbuffington** [hypeJunction/hypeDiscussions#7]
Many of your cool mods you are using evi ?

i.e. 
Undefined variable: component" in file hypeInteractions/views/default/page/components/interactions.php (line 73)
etc...
hypeDiscussions/views/default/forms/discussion/reply/save.php (line 23)

**elgg_view_input()** is deprecated. 

**Use elgg_view_field()**

If you could update all your mods to use the new function it would greatly be appreciated.

Thank You for all your hard work we appreciate it :)

**Comment by hypeJunction** [comment]
Deprecation notices are just notices. You can continue using the plugins
